zb.hikari.jdbc-url: jdbc:mysql://192.168.1.66:3307/test?passwordCharacterEncoding=latin1&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&connectTimeout=10000&socketTimeout=600000&allowPublicKeyRetrieval=true
zb.hikari.username: root
zb.hikari.password: 982003834
