#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring-boot-demo
#    username: root
#    password: root
#    hikari:
#      data-source-properties:
#        useSSL: false
#        serverTimezone: GMT+8
#        useUnicode: true
#        characterEncoding: utf8
#        # 这个必须要加，否则 Activiti 自动建表会失败
#        nullCatalogMeansCurrent: true
#  activiti:
#    history-level: full
#    db-history-used: true

zb.hikari.jdbc-url: jdbc:mysql://localhost:3307/test?passwordCharacterEncoding=latin1&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&connectTimeout=10000&socketTimeout=600000&allowPublicKeyRetrieval=true
zb.hikari.username: root
zb.hikari.password: 982003834
