server:
  port: 8081
  servlet:
    context-path: /hikari-demo
spring:
  profiles:
    active: taiwindows
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# 通过 JMX 或 Actuator 监控连接池：
# 访问 http://localhost:8081/high/mtcs/hikaricp.connections.active 查看活跃连接数
management:
  metrics:
    enable:
      hikari: true        # 启用 HikariCP 指标收集
  endpoint:
    health:
      show-components: when_authorized
  endpoints:
    web:
      base-path: /high
      path-mapping:
        health: heal
        metrics: mtcs
        datasource: ds
      exposure:
        include: jolokia,health,metrics,datasource
#        include: "*"


zb.hikari.maximum-pool-size: 10
zb.hikari.minimum-idle: 5
zb.hikari.idle-timeout: 30000
zb.hikari.connection-timeout: 5000
zb.hikari.max-lifetime: 1800000
zb.hikari.keepalive-time: 90000
